// type类型字典

export const DEF_OPEN_KEYS = 'DEF_OPEN_KEYS'
export const SET_DEF_OPEN_KEYS = 'SET_DEF_OPEN_KEYS'
export const DEF_SELECTED_KEYS = 'DEF_SELECTED_KEYS'
export const SET_DEF_SELECTED_KEYS = 'SET_DEF_SELECTED_KEYS'
export const SET_MENU_COLLAPSED = 'SET_MENU_COLLAPSED'